export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2c4d45",
        "on-primary-fixed-variant": "#484645",
        "secondary-fixed": "#ffdbd2",
        "on-secondary": "#ffffff",
        "outline-variant": "#ccc5bd",
        "surface-container-low": "#f5f3ee",
        "surface-dim": "#dbdad5",
        "background": "#fbf9f4",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2dd",
        "on-surface": "#1b1c19",
        "primary-container": "#1c1b1a",
        "surface-tint": "#605e5c",
        "tertiary-fixed-dim": "#aacec3",
        "inverse-primary": "#cac6c4",
        "primary-fixed-dim": "#cac6c4",
        "tertiary-fixed": "#c6eadf",
        "on-secondary-fixed": "#3c0800",
        "on-background": "#1b1c19",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#6a1500",
        "error": "#ba1a1a",
        "inverse-surface": "#30312e",
        "error-container": "#ffdad6",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "on-surface-variant": "#4a4640",
        "on-tertiary-container": "#698b81",
        "tertiary-container": "#00201a",
        "on-error-container": "#93000a",
        "surface": "#fbf9f4",
        "surface-container": "#f0eee9",
        "on-primary-container": "#868382",
        "secondary-fixed-dim": "#ffb4a2",
        "on-secondary-fixed-variant": "#881f01",
        "secondary": "#aa3618",
        "on-tertiary-fixed": "#00201a",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f1ec",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "on-primary-fixed": "#1c1b1a",
        "secondary-container": "#fe7350",
        "outline": "#7b766f",
        "primary-fixed": "#e6e2df",
        "primary": "#000000"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "container-padding-mobile": "20px",
        "container-padding-desktop": "48px",
        "section-gap": "64px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "data-mono": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["20px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
